### ISSUE TITLE
Error loading module: azure_ai_foundry

### ISSUE THREAD

**Issue by elsewhat** [owndev/Open-WebUI-Functions#31]
### Bug title

Error loading module: azure_ai_foundry - No module named 'open_webui'/:No Pipeline class found in azure_ai_foundry

### Describe the bug

Setting up Open webui locally with pipeline connection towards Azure AI foundry. 

Pipelines functionality in OpenWebui is active, but when uploading azure_ai_foundry.py there are no pipelines or models found.

Log output in pipelines docker container
```
INFO: 172.19.0.3:38192 - "GET /pipelines HTTP/1.1" 200 OK
[https://raw.githubusercontent.com/owndev/Open-WebUI-Functions/master/pipelines/azure/azure_ai_foundry.py⁠](https://raw.githubusercontent.com/owndev/Open-WebUI-Functions/master/pipelines/azure/azure_ai_foundry.py)
Error loading module: azure_ai_foundry
No module named 'open_webui'
INFO: 172.19.0.3:46908 - "POST /pipelines/add HTTP/1.1" 200 OK
WARNING:root:No Pipeline class found in azure_ai_foundry
```

The no module name comes from the line 
https://github.com/owndev/Open-WebUI-Functions/blob/master/pipelines/azure/azure_ai_foundry.py#L24
```
from open_webui.env import AIOHTTP_CLIENT_TIMEOUT, SRC_LOG_LEVELS
```

If hardcode those values instead of importing I still get the following error in the logs
```
Loaded module: azure_ai_foundry
Error loading module: azure_ai_foundry
No Pipeline class found
INFO: 172.19.0.3:35950 - "POST /pipelines/upload HTTP/1.1" 200 OK
WARNING:root:No Pipeline class found in azure_ai_foundry
```

Had expected there to be new models after the import of azure_ai_foundry, but this list is still empty. 

### Steps to reproduce

my docker-compose.yaml filee
```
services:
  open-webui:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-open-webui:1.0.0
    container_name: my-open-webui
    env_file:
      - .env    
    volumes:
      - open-webui:/app/backend/data
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

  pipelines:
      image: ghcr.io/open-webui/pipelines:main
      volumes:
        - pipelines:/app/pipelines
      restart: always
      environment:
        - PIPELINES_API_KEY=0p3n-w3bu!

volumes:
  open-webui: {}
  pipelines: {}
```

.env file (tested adding to the pipelines container as well, but get the same issue)
```
AZURE_AI_API_KEY=<key from Azure AI Foundry>
AZURE_AI_ENDPOINT="https://<my azure resource>.openai.azure.com/models/chat/completions?api-version=2025-01-01-preview"
AZURE_AI_MODEL="gpt-4.1;gpt4.1-nano"
AZURE_AI_MODEL_IN_BODY=true
USE_PREDEFINED_AZURE_AI_MODELS=false
AZURE_AI_USE_AUTHORIZATION_HEADER=false
```

### Environment

Docker
Openwebui 0.6.7 (latest commit https://github.com/open-webui/open-webui/commit/a3bb7df61058e690a76cebb7681bd5390e77d226)
